### ISSUE TITLE
kvm list command display error - Method invocation failed because [System.String[]] doesn't contain a method named 'Contains'.

### ISSUE THREAD

**Issue by anuraj** [aspnet/kvm#106]
KVM list command displays **Method invocation failed because [System.String[]] doesn't contain a method named 'Contains'.** error on Windows 7. 

K Runtime Environment Version Manager - Build 10017

**Comment by Praburaj** [comment]
I updated the `kvm` scripts in home repo. Latest scripts should have fixed the problem.

**Comment by MrSnot** [comment]
@anuraj :+1: thanks for the help
