### ISSUE TITLE
When kre is installed on global, run k web returns "'D:\Program' is not recognized as an internal or external command..." 

### ISSUE THREAD

**Issue by Xiaohongt** [aspnet/kvm#108]
Repro steps:
1). Install kre on global, e.g. kvm upgrade -x86 -r CoreCLR -g 
2). On Project K web app location, run k web

Actual result:
k web returns like "'D:\Program' is not recognized as an internal or external command, operable program or batch file." 

Expected result:
k web can run

**Comment by Praburaj** [comment]
This is fixed now.
