### ISSUE TITLE
k: command not found, kpm: command not found

### ISSUE THREAD

**Issue by KaBaJIeP** [aspnet/kvm#118]
vpla@ubuntu-node:~$ kvm list

Active Version              Runtime Location             Alias
------ -------              ------- --------             -----
       1.0.0-beta1          Mono    ~/.kre/packages
       -g                   Mono    ~/.kre/packages
======================================================

vpla@ubuntu-node:~$ cd vnext/Home/samples/HelloWeb/
vpla@ubuntu-node:~/vnext/Home/samples/HelloWeb$ kpm restore
No command 'kpm' found, did you mean:
 Command 'bpm' from package 'bpm-tools' (universe)
 Command 'pm' from package 'powerman' (universe)
 Command 'cpm' from package 'cpm' (universe)
 Command 'gpm' from package 'gpm' (universe)
 Command 'dpm' from package 'dpm-server-postgres' (universe)
 Command 'dpm' from package 'dpm-server-mysql' (universe)
 Command 'epm' from package 'epm' (universe)
 Command 'kcm' from package 'heimdal-kcm' (universe)
 Command 'apm' from package 'apmd' (universe)
 Command 'rpm' from package 'rpm' (main)
 Command 'kdm' from package 'kdm' (universe)
 Command 'kvpm' from package 'kvpm' (universe)
 Command 'kvm' from package 'qemu-kvm' (main)
 Command 'npm' from package 'npm' (universe)
kpm: command not found
vpla@ubuntu-node:~/vnext/Home/samples/HelloWeb$ ^C
vpla@ubuntu-node:~/vnext/Home/samples/HelloWeb$ k kestrel
k: command not found

==============================================================

vpla@ubuntu-node:~/vnext/Home/samples/HelloWeb$ kvm upgrade
Determining latest version
Latest version is 1.0.0-beta1
KRE-Mono.1.0.0-beta1 already installed.
Cannot find KRE-Mono.1.0.0-beta1, do you need to run 'kvm install 1.0.0-beta1'?

===============================================================

Ubuntu 14.04 LTS
Mono JIT compiler version 3.99.0
branch dev and using nuget.config from this url -> https://www.myget.org/F/aspnetvnext

All actions was doing by manual(https://github.com/aspnet/home). What i missing?

**Comment by thadiggitystank** [comment]
FWIW @KaBaJIeP -- I had this same issue when trying to install kvm. My first attempt failed due to 'unzip' not being installed, which resulted in a broken install with the error message you described. 

After installing unzip, I removed the ~/.kre directory and reinstalled kvm, and everything is working as I would expect now.

**Comment by Praburaj** [comment]
latest `kvm` scripts will check for presence of `unzip`. When did you install the `kvm` scripts you have on your machine. As @thadiggitystank suggested try a bit of cleanup and reinstall latest kvm to see if that addresses the issue.

**Comment by KaBaJIeP** [comment]
by this guide - all works
http://habrahabr.ru/post/243773/
