### ISSUE TITLE
Confusing error when unzip not installed

### ISSUE THREAD

**Issue by ryan1234** [aspnet/kvm#119]
I looked through older issues and couldn't find this exact problem, so I figured I'd submit it.

I installed mono, KVM, and everything else needed to get vNext running on Linux. Everything except for 
the unzip package in Ubuntu 14.04 LTS.

The error I got when trying to run 'kvm upgrade' was: Cannot find KRE-Mono.1.0.0-beta1, do you need to run 'kvm install 1.0.0-beta1'?

Because I was missing unzip the installation got into a broken state. I had to delete the .kre directory in my home directory and re-run kvm.sh after installing the unzip package.

It seems there was better messaging before about missing the unzip package in an earlier version of kvm.sh? Is there any way to not do any work if unzip is missing rather than do some work, get into broken state and give odd error?

**Comment by Praburaj** [comment]
We seem to be doing a check for `unzip` before unzipping the package. Could you check if your `~./kre/kvm/kvm.sh` have these lines? 

https://github.com/aspnet/kvm/blob/dev/src/kvm.sh#L101

**Comment by Praburaj** [comment]
Try pulling the latest `kvm.sh` from home repo to get the fix.
