### ISSUE TITLE
Rename to dotnetsdk

### ISSUE THREAD

**Issue by anurse** [aspnet/kvm#137]
* [ ] Rename the repository to aspnet/dotnetsdk
* [ ] Rename the scripts to dotnetsdk.{cmd|ps1|sh}
* [ ] Big-ol find-replace
* [ ] Update aspnet/Home and aspnet/dotnetsdk READMEs

**Comment by davidfowl** [comment]
Yep! The changes are coming into the KRuntime right now.

Install locations will be:

```
./dotnet/runtimes/dotnet-{clr/coreclr}-{arch}/{version}/
./dotnet/runtimes/dotnet-mono/{version}/
```
/cc @danroth27 @lodejard @DamianEdwards @Eilon 

How does it look to you?

**Comment by Eilon** [comment]
`./dotnet/...` or `./.dotnet/...`?

**Comment by davidfowl** [comment]
oops:

```/.dotnet```

**Comment by Eilon** [comment]
.thought.so
