### ISSUE TITLE
kvm install of a X64 package throws this error though the install is successful

### ISSUE THREAD

**Issue by Praburaj** [aspnet/kvm#38]
```kvm install d:\KRE-svr50-x64.1.0.0-alpha3-10156.nupkg -alias fromnupkg1```
Unpacking to C:\Users\prabht\.kre\packages\temp
Installing to C:\Users\prabht\.kre\packages\KRE-svr50-x64.1.0.0-alpha3-10156
`Cannot find KRE-svr50-x86.1.0.0-alpha3-10156, do you need to run 'kvm install 1.0.0-alpha3-10156'?`
Setting alias 'fromnupkg1' to 'KRE-svr50-x86.1.0.0-alpha3-10156'

**Comment by Praburaj** [comment]
This does not reproduce any more. @graemechristie - do you know if this issue was fixed with any PR?

**Comment by graemechristie** [comment]
Quite possibly #57 or even #68.
