### ISSUE TITLE
Powershell script to setup kvm on Windows does not work when run from a normal command prompt

### ISSUE THREAD

**Issue by balachir** [aspnet/kvm#48]
1. Clean machine
2. Copy powershell script from github.com/aspnet/Home
3. Open a new command prompt and paste it

ACTUAL
Prompts to be elevated, but even if you elevate, you get some red text in the powershell window and kvm does not get setup properly.

I have a video of this if you need

EXPECTED
kvm to be available

**Comment by Praburaj** [comment]
@balachir - I am unable to reproduce this issue with latest. Do you still reproduce this issue? Or else can we close this item?

**Comment by balachir** [comment]
@Praburaj , it's working fine for me now. Closing.
