### ISSUE TITLE
Installing svrc before svr doesn't work

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/kvm#51]
On a clean machine with no KRE installed yet, if you try to run:
kvm install KRE-svrc50-x86.1.0.0-alpha4-10309.nupkg
with the .nupkg in that location of course.
The package fails to install because in the Requested-VersionOrAlias function it looks for the alias folder which doesn't exist yet, and by default sets the platform to svr50 when we are trying to use svrc50

**Comment by Praburaj** [comment]
@BrennanConroy - this bug does not seem to reproduce with latest bits. Could you try if it repros for you?

**Comment by BrennanConroy** [comment]
This looks like it is no longer an issue.
