### ISSUE TITLE
[dev] kvm.sh does display alias  correctly with new changes

### ISSUE THREAD

**Issue by suhasj** [aspnet/kvm#61]
With the new changes to support Mono instead of mono45, the alias column does not display the aliases correctly. 

Repro:
1. No default alias
- install kre and run 'kvm list'. The Alias field is not populated to show default

2. Incorrect alias
- I had two versions of KRE installed 10429 and 10424
- I set 10429 as 'default' and 10424 'olddefault'
- running 'kvm alias' displayed them fine
- when i ran 'kvm unalias olddefault' it removed the alias as expected
- but 'kvm list' should the default alias to 10424 and not 10429

**Comment by Praburaj** [comment]
@suhasj if this issue is resolved can we close this bug?
