### ISSUE TITLE
maximum nested function level reached

### ISSUE THREAD

**Issue by mihasic** [aspnet/kvm#75]
At some point after installing the latest kvm I've got the 'maximum nested function level reached' error.
Could not log in till removed the line from shell startup:
[ -s "/home/mike/.kre/kvm/kvm.sh" ] && . "/home/mike/.kre/kvm/kvm.sh" # Load kvm

Now can reproduce by running:
~/dev/Home/samples/HelloMvc (master ✔) ᐅ source ~/.kre/kvm/kvm.sh
local:215: job table full or recursion limit exceeded
local:1: maximum nested function level reached

And can't type anything anymore:
~/dev/Home/samples/HelloMvc (master) ᐅ
local:2: maximum nested function level reached
local:1: maximum nested function level reached
~/dev/Home/samples/HelloMvc (master) ᐅ
local:1: maximum nested function level reached

System:
Ubuntu Server 14.04.1 with all the updates. With zsh, oh-my-zsh, ubuntu-desktop, mono-3.10.0 installed from tarball.

**Comment by Praburaj** [comment]
This seems to be fixed with https://github.com/aspnet/kvm/pull/70.
