### ISSUE TITLE
Installation in OS X 10.10 with zsh crashes sourcing kvm.sh

### ISSUE THREAD

**Issue by andresclari** [aspnet/kvm#83]
On OS X 10.10 after installing kvm via homebrew, can't source ´kvm.sh´. The whole shell crashes when attempting to source the script, so I can't attach any error message.

Tried disabling everything on my zshrc file, including oh-my-zsh.

Shell: zsh 2.0.7

**Comment by Praburaj** [comment]
`kvm` scripts have been updated in the home repo. `brew install` should automatically pick up these updated scripts from home repo. So the issue will be addressed.
